import type { LyricPreset, LyricStyle } from "./types";

export const defaultLyricStyle: LyricStyle = {
  presetId: "night-tilt",
  x: 8,
  y: -2,
  scale: 1,
  rotateZ: -2,
  rotateX: 16,
  rotateY: -18,
  skewX: 0,
  skewY: 0,
  perspective: 980,
  opacity: 1,
  fontSize: 56,
  color: "#a7e0ff",
  stroke: "rgba(0,0,0,.35)",
  shadow: 24,
  glow: 20,
  inactiveColor: "#e5e2e1",
  inactiveOpacity: 0.44,
  lineGap: 22,
  backgroundBlur: 8,
  backgroundDim: 62,
  backgroundSaturation: 118,
  panelOpacity: 38,
  scanline: false,
  coverEnabled: true,
  coverX: -26,
  coverY: -5,
  coverSize: 210,
  coverRotationSeconds: 12,
  lyricDisplayMode: "scroll",
  lyricOffset: 0,
  layoutLocked: true,
};

export const lyricPresets: LyricPreset[] = [
  {
    id: "night-tilt",
    name: "QQ \u5531\u7247",
    style: defaultLyricStyle,
  },
  {
    id: "anime-memory",
    name: "\u52a8\u6f2b\u56de\u5fc6",
    style: {
      ...defaultLyricStyle,
      presetId: "anime-memory",
      x: 18,
      y: -4,
      scale: 0.9,
      rotateZ: 0,
      rotateX: 0,
      rotateY: 0,
      perspective: 900,
      fontSize: 34,
      color: "#f7fbff",
      inactiveColor: "#d8d6dc",
      inactiveOpacity: 0.42,
      lineGap: 12,
      backgroundBlur: 1,
      backgroundDim: 58,
      backgroundSaturation: 88,
      panelOpacity: 24,
      scanline: false,
      coverEnabled: true,
      coverX: -24,
      coverY: -2,
      coverSize: 230,
      coverRotationSeconds: 16,
    },
  },
  {
    id: "heart-share",
    name: "\u4eca\u65e5\u5206\u4eab",
    style: {
      ...defaultLyricStyle,
      presetId: "heart-share",
      x: -12,
      y: -4,
      scale: 0.88,
      rotateZ: -8,
      rotateX: 8,
      rotateY: -10,
      fontSize: 42,
      color: "#f8fbff",
      inactiveColor: "#8fa5bd",
      inactiveOpacity: 0.52,
      backgroundBlur: 3,
      backgroundDim: 26,
      backgroundSaturation: 72,
      panelOpacity: 30,
      coverEnabled: true,
      coverX: 26,
      coverY: -12,
      coverSize: 300,
      coverRotationSeconds: 14,
    },
  },
  {
    id: "raster-water",
    name: "\u84dd\u8272\u5149\u6805",
    style: {
      ...defaultLyricStyle,
      presetId: "raster-water",
      x: 12,
      y: -8,
      scale: 0.9,
      rotateZ: 0,
      rotateX: 12,
      rotateY: -24,
      fontSize: 38,
      color: "#c7fff8",
      inactiveColor: "#a9d8ee",
      inactiveOpacity: 0.58,
      backgroundBlur: 2,
      backgroundDim: 54,
      backgroundSaturation: 148,
      panelOpacity: 42,
      scanline: true,
      coverEnabled: true,
      coverX: -29,
      coverY: 10,
      coverSize: 180,
      coverRotationSeconds: 10,
    },
  },
];

export function normalizeLyricStyle(style?: Partial<LyricStyle>): LyricStyle {
  return { ...defaultLyricStyle, ...(style ?? {}) };
}
